<h2>Links Úteis</h2>
<h3>1. Leis</h3>
<div>
	<p>
		<strong>Sistema Sistec</strong>
		<li><a target="_blank"  href="http://sistec.mec.gov.br">http://sistec.mec.gov.br</a></li>
	</p>
</div>
<div>
	<p>
		<strong>Portal Sistec</strong>
		<li><a target="_blank"  href="http://sitesistec.mec.gov.br">http://sitesistec.mec.gov.br</a></li>
	</p>	
</div>
<div>
	<p>
		<strong>Portal Pronatec</strong>
		<li><a target="_blank"  href="http://pronatec.mec.gov.br">http://pronatec.mec.gov.br</a></li>
	</p>	
</div>
<div>
	<p>
		<strong>Adesão ao Pronatec</strong>
		<li><a target="_blank"  href="http://pronatecadesao.mec.gov.br/">http://pronatecadesao.mec.gov.br/</a></li>
	</p>	
</div>
<div>
	<p>
		<strong>Relatórios Pronatec</strong>
		<li><a target="_blank"  href="http://spp.mec.gov.br/relatorio">http://spp.mec.gov.br/relatorio</a></li>
	</p>	
</div>