<h2>Portarias do Pronatec</h2>

<h3>1. Leis</h3>
<div>
	<p><strong>2011</strong></p>
	<li><a href="http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12513.htm">Lei n° 12.513, de 26 de Outubro de 2011</a></li>
	<p style="margin-left: 60px;">Institui o Programa Nacional de Acesso ao Ensino Técnico e Emprego – PRONATEC.</p>
	<p><strong>2013</strong></p>
	<li><a href="http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/Lei/L12816.htm">Lei nº 12.816, de 05 de junho de 2013</a></li>
	<p style="margin-left: 60px;">Altera as Leis nº 12.513, de 26 de outubro de 2011(Pronatec); nº 9.250, de 26 de dezembro de 1995 (bolsas recebidas pelos servidores, no âmbito do Pronatec); nº 8.212, de 24 de julho de 1991 (incidência da contribuição previdenciária ); dispõe sobre o apoio da União às redes públicas de educação básica na aquisição de veículos para o transporte escolar; e permite que os entes federados usem o registro de preços para a aquisição de bens e contratação de serviços em ações e projetos educacionais.</p>
	<p style="margin-left: 60px;">&nbsp;</p>
</div>

<h3>2. Portarias MEC</h3>
<div>
	<p><strong>2012</strong></p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_185.pdf">Portaria MEC N° 185, de 12 de março de 2012</a></li>
	<p style="margin-left: 60px;">Fixa diretrizes para execução da Bolsa-Formação no âmbito do Pronatec.</p>
	<p><strong>2013</strong></p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria1_160_050313.pdf">Portaria MEC N° 160, de 05 de março de 2013</a></li>
	<p style="margin-left: 60px;">Dispõe sobre a habilitação de&nbsp;instituições e sobre a adesão das respectivas mantenedoras ao Pronatec.</p>
	<li>&nbsp;<a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_161_060313.pdf">Portaria N° 161, de 06 de março de 2013</a></li>
	<p style="margin-left: 60px;">Dispõe sobre o Fundo de Financiamento Estudantil, na modalidade de educação profissional e tecnológica.</p>
	<li><p><a href="http://pronatec.mec.gov.br/images/stories/pdf/port_168_070313.pdf">Portaria MEC N° 168, de 07 de março de 2013</a></p></li>
	<p style="margin-left: 60px;">Dispõe sobre a oferta da Bolsa-Formação no âmbito do Pronatec.</p>
	<li><p><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_362_26042013.pdf">Portaria MEC Nº 362, de 26 de Abril de 2013</a></p></li>
	<p style="margin-left: 60px;">Dispõe sobre alteração no art. 74 da Portaria MEC nº 168, de 07 de março de 2013.</p>
	<li>
	<p><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_20.pdf">Portaria SETEC/MEC Nº 20, de 27 de junho de 2013</a></p>
	</li>
	<p style="margin-left: 60px;">Dispoõe sobre a Tabela de mapeamento de cursos técnicos para oferta na forma subsequente por intermédio da Bolsa-Formação Estudante e correlação com cursos de graduação.</p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_1007_09102013.pdf">Portaria MEC Nº 1007, de 09 de outubro de 2013</a></li>
	<p style="margin-left: 60px;">Altera a Portaria MEC nº 168, de 07 de março de 2013, que dispõe sobre a oferta da Bolsa-Formação no âmbito do Pronatec.</p>
	<p><strong>2014</strong></p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/port_setec_01_2014_tab_map.pdf">Portaria SETEC/MEC n° 01 , de 29 de Janeiro de 2014</a></li>
	<p style="margin-left: 60px;">Altera a Portaria SETEC/MEC nº 20, de 27 de junho de 2013, que aprova a Tabela de Mapeamento de cursos técnicos para oferta no âmbito do Pronatec.</p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_114.pdf">Portaria MEC nº 114, de 7 de Fevereiro de 2014</a></li>
	<p style="margin-left: 60px;">Altera a Portaria MEC nº 168, de 7 de março de 2013, que dispõe sobre a oferta da Bolsa-Formação no âmbito do Pronatec.</p>
	<li><a href="http://pronatec.mec.gov.br/images/port_701_130814.pdf">Portaria nº 701, de 13 de agosto de 2014</a></li>
	<p style="margin-left: 60px;">Altera a Portaria MEC nº 160, de 5 de março de 2013, que dispõe sobre a habilitação de instituições e sobre a adesão das respectivas mantenedoras ao Pronatec.</p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_991.pdf">Portaria nº 991, de 25 de novembro de 2014&nbsp;</a></li>
	<p style="margin-left: 60px;">Altera a Portaria MEC nº 168, de 7 de março de 2013, que dispõe sobre a oferta da Bolsa-Formação no âmbito do Pronatec.</p>
	<p style="margin-left: 60px;">&nbsp;</p>
</div>
<h3>3. Guia Pronatec de Cursos FIC</h3>
<div>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_1568.pdf">Portaria MEC N° 1.568, de 3 de Novembro de 2011</a></li>
	<p style="margin-left: 60px;">Aprovar o Guia Pronatec de Cursos de Formação Inicial e Continuada.</p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/portaria_1232_.pdf">Portaria MEC nº 1.232, de 05 de outubro de 2012</a></li>
	<p style="margin-left: 60px;">Aprovar o Guia Pronatec de Cursos de Formação Inicial e Continuada.</p>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/guia_pronatec_fic_terceira_ed.pdf">Portaria MEC nº 899 de 20 de setembro de 2013</a></li>
	<p style="margin-left: 60px;">Aprovar o Guia Pronatec de Cursos de Formação Inicial e Continuada.</p>
	<p>&nbsp;</p>
</div>
<h3>4. Manual de Gestão da Bolsa-Formação</h3>
<div>
	<li><a href="http://pronatec.mec.gov.br/images/stories/pdf/manual_bolsa_formacao.pdf">Manual de Gestão da Bolsa-Formação 2011</a></li>
</div>
<h3>5. Resoluções FNDE</h3>
<div>
	<p><strong>5.1. Rede Federal</strong></p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000062&amp;seq_ato=000&amp;vlr_ano=2011&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 62, de 11 de novembro de 2011</a></li>
	<p style="margin-left: 60px;">Critérios e procedimentos para a transferência de recursos e prestação de contas para a oferta da bolsa-formação em cursos vinculados aos serviços nacionais de aprendizagem, no âmbito do Pronatec</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000072&amp;seq_ato=000&amp;vlr_ano=2011&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 72, de 20 de dezembro de 2011</a></li>
	<p style="margin-left: 60px;">Altera a Resolução CD/FNDE nº 62, de 11 de novembro de 2011.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000004&amp;seq_ato=000&amp;vlr_ano=2012&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 4, de 16 de março de 2012</a></li>
	<p style="margin-left: 60px;">Altera a Resolução CD/FNDE nº 62, de 11 de novembro de 2011.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000006&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 6, de 12 de março de 2013</a></li>
	<p style="margin-left: 60px;">Altera a Resolução/CD/FNDE nº 04, de 16 de março de 2012, que estabelece critérios e procedimentos para a descentralização de créditos orçamentários às Instituições da Rede Federal de Educação Profissional, Científica e Tecnológica, visando à oferta de Bolsa-Formação no âmbito do Pronatec.</p>
	<p><strong>5.2. Redes Estaduais, Municipais e Distrital</strong></p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000023&amp;seq_ato=000&amp;vlr_ano=2012&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 23, de 28 de junho de 2012</a></li>
	<p style="margin-left: 60px;">Estabelece orientações, critérios e procedimentos para a transferência de recursos financeiros e prestação de contas, ao Distrito Federal e aos Estados visando à oferta de Bolsa-Formação no âmbito do Pronatec.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000008&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 8, de 20 de março de 2013</a></li>
	<p style="margin-left: 60px;">Estabelece orientações, critérios e procedimentos para a transferência de recursos financeiros e prestação de contas, ao Distrito Federal e aos Estados visando à oferta de Bolsa-Formação no âmbito do Pronatec.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000039&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 39, de 10 de outubro de 2013</a></li>
	<p style="margin-left: 60px;">Altera a Resolução CD/FNDE nº 8, de 20 de março de 2013, que estabelece orientações, critérios e procedimentos para a transferência de recursos financeiros e prestação de contas, ao Distrito Federal e aos Estados visando à oferta de Bolsa-Formação no âmbito do Pronatec.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000003&amp;seq_ato=000&amp;vlr_ano=2014&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 3, de 6 de março de 2014</a></li>
	<p style="margin-left: 60px;">Altera o art. 3º da Resolução nº 8, de 20 de março de 2013,&nbsp;que estabelece orientações, critérios e procedimentos para a transferência de recursos financeiros e prestação de contas, ao Distrito Federal e aos Estados visando à oferta de Bolsa-Formação no âmbito do Pronatec.</p>
	<p><strong>5.3. SNA</strong></p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000061&amp;seq_ato=000&amp;vlr_ano=2011&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 61, de 11 de novembro de 2011</a></li>
	<p style="margin-left: 60px;">Estabelece orientações, critérios e procedimentos para a transferência de recursos financeiros e prestação de contas visando à oferta de Bolsa-Formação em cursos vinculados aos serviços nacionais de aprendizagem,&nbsp;no âmbito do Pronatec.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000066&amp;seq_ato=000&amp;vlr_ano=2011&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 66, de 25 de novembro de 2011</a></li>
	<p style="margin-left: 60px;">Altera a Resolução CD/FNDE nº 61, de 11 de novembro de 2011.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000074&amp;seq_ato=000&amp;vlr_ano=2011&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 74, de 28 de dezembro de 2011</a></li>
	<p style="margin-left: 60px;">Altera o § 1º do Art. 9º e a numeração dos artigos finais, a partir do Art. 20 da Resolução CD/FNDE nº 61 de 11 de novembro de 2011.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000003&amp;seq_ato=000&amp;vlr_ano=2012&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 3, de 16 de março de 2012</a></li>
	<p style="margin-left: 60px;">Altera a Resolução CD/FNDE nº 61, de 11 de novembro de 2011.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000033&amp;seq_ato=000&amp;vlr_ano=2012&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 33, de 15 de agosto de 2012</a></li>
	<p style="margin-left: 60px;">Altera o § 4º do art. 8º da Resolução CD/FNDE nº 3, de 16 de março de 2012.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000007&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 7, de 20 de março de 2013</a></li>
	<p style="margin-left: 60px;">Estabelece orientações, critérios e procedimentos para a transferência de recursos financeiros e prestação de contas visando à oferta de Bolsa-Formação em cursos vinculados aos serviços nacionais de aprendizagem, no âmbito do Pronatec,&nbsp;a partir de 2013.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000002&amp;seq_ato=000&amp;vlr_ano=2014&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 2, de 6 de março de 2014</a></li>
	<p style="margin-left: 60px;">Altera o art. 3º da Resolução nº 7, de 20 de março de 2013, que estabelece procedimentos para a transferência de recursos financeiros aos serviços nacionais de aprendizagem, visando à oferta de Bolsa-Formação no âmbito do Pronatec.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000055&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=FNDE/MEC">Resolução/CD/FNDE nº 55, de 13 de dezembro de 2013</a></li>
	<p style="margin-left: 60px;">Estabelece procedimentos para a transferência de recursos financeiros da Bolsa-Formação do Pronatec aos serviços nacionais de aprendizagem participantes da Rede e-Tec Brasil, para que estes ofertem educação profissional e tecnológica na modalidade a distância, executem e prestem contas desses recursos, a partir de 2013.</p>
	<p><strong>5.4. IES e ETNM Privadas</strong></p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000030&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=CD/FNDE/MEC">Resolução/CD/FNDE nº 30, de 5 de julho de 2013</a></li>
	<p style="margin-left: 60px;">Estabelece procedimentos para o pagamento da Bolsa-Formação Estudante às mantenedoras de instituições privadas de ensino superior e de educação profissional técnica de nível médio, ofertada na forma subsequente, no âmbito do Pronatec.</p>
	<li><a href="https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&amp;sgl_tipo=RES&amp;num_ato=00000050&amp;seq_ato=000&amp;vlr_ano=2013&amp;sgl_orgao=FNDE/MEC">Resolução/CD/FNDE nº 50, de 11 de dezembro de 2013</a></li>
	<p style="margin-left: 60px;">Altera os arts. 2º, 3º, 5º e 6º da Resolução CD/FNDE no 30, de 5 de julho de 2013, que estabelece procedimentos para o pagamento da Bolsa-Formação Estudante a mantenedoras de instituições privadas de ensino superior e de educação profissional técnica de nível médio, ofertada na forma subsequente, no âmbito Pronatec.&nbsp;</p>
</div>
<h3 class="pergunta" style="cursor: pointer;">&nbsp;</h3> 




</div>