<h2>Pronatec</h2>

<p>
O Programa Nacional de Acesso ao Ensino Técnico e Emprego (Pronatec) foi criado pelo Governo Federal, em 2011, por meio da Lei 11.513/2011, com o objetivo de expandir, interiorizar e democratizar a oferta de cursos de educação profissional e tecnológica no país, além de contribuir para a melhoria da qualidade do ensino médio público.
O Pronatec busca ampliar as oportunidades educacionais e de formação profissional qualificada aos jovens, trabalhadores e beneficiários de programas de transferência de renda.
Os cursos, financiados pelo Governo Federal, são ofertados de forma gratuita por instituições da Rede Federal de Educação Profissional, Científica e Tecnológica e das redes estaduais, distritais e municipais de educação profissional e tecnológica. Também são ofertantes as instituições do Sistema S, como o SENAI, SENAT, SENAC e SENAR. A Partir de 2013, as instituições privadas, devidamente habilitadas pelo Ministério da Educação, também passaram a ser ofertantes dos cursos do Programa.
De 2011 a 2014, por meio do Pronatec, foram realizadas mais de 8 milhões de matrículas, entre cursos técnicos e de formação inicial e continuada.
</p>
<p>
	Objetivos:
</p>
<li>expandir, interiorizar e democratizar a oferta de cursos de educação profissional técnica de nível médio e de cursos de formação inicial e continuada ou qualificação profissional presencial e a distância;</li>
<li>construir, reformar e ampliar as escolas que ofertam educação profissional e tecnológica nas redes estaduais;</li>
<li>aumentar as oportunidades educacionais aos trabalhadores por meio de cursos de formação inicial e continuada ou qualificação profissional;</li>
<li>aumentar a quantidade de recursos pedagógicos para apoiar a oferta de educação profissional e tecnológica;</li>
<li>melhorar a qualidade do ensino médio</li>

</p>
<div class="col-md-12">
  <div class="row">
    <a class="btn btn-primary" data-toggle="collapse" href="#col23" style="width: 600px" aria-expanded="false" aria-controls="col23">
      Programa Brasil Profissionalizado
    </a>
    <!-- Conteudo -->
    <div class="collapse" id="col23">
      <div class="well">
        O Programa Brasil Profissionalizado destina-se à ampliação da oferta e ao fortalecimento da educação profissional e tecnológica integrada ao ensino médio nas redes estaduais, em parceria com o Governo Federal.
      </div>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="row">
    <a class="btn btn-primary" data-toggle="collapse" href="#col24" style="width: 600px" aria-expanded="false" aria-controls="col24">
      Rede e-Tec Brasil
    </a>
    <!-- Conteudo -->
    <div class="collapse" id="col24">
      <div class="well">
        Na Rede e-Tec Brasil são oferecidos gratuitamente cursos técnicos e de formação inicial e continuada ou de qualificação profissional, na modalidade a distância. Poderão oferecer cursos a distância as instituições da Rede Federal de Educação Profissional, Científica e Tecnológica; as unidades de ensino dos serviços nacionais de aprendizagem (SENAI, SENAC, SENAR e SENAT); e instituições de educação profissional vinculadas aos sistemas estaduais de ensino
      </div>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="row">
    <a class="btn btn-primary" data-toggle="collapse" href="#col25" style="width: 600px" aria-expanded="false" aria-controls="col25">
      Acordo de Gratuidade com os Serviços Nacionais de Aprendizagem
    </a>
    <!-- Conteudo -->
    <div class="collapse" id="col25">
      <div class="well">
        O Acordo de Gratuidade tem por objetivo ampliar, progressivamente, a aplicação dos recursos do SENAI, do SENAC, do SESC e do SESI, recebidos da contribuição compulsória, em cursos técnicos e de formação inicial e continuada ou de qualificação profissional, em vagas gratuitas destinadas a pessoas de baixa renda, com prioridade para estudantes e trabalhadores
      </div>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="row">
    <a class="btn btn-primary" data-toggle="collapse" href="#col26" style="width: 600px" aria-expanded="false" aria-controls="col26">
      Bolsa-Formação 
    </a>
    <!-- Conteudo -->
    <div class="collapse" id="col26">
      <div class="well">
        Além das iniciativas voltadas ao fortalecimento do trabalho das redes de educação profissional e tecnológica existentes no país, o Pronatec criou a Bolsa-Formação, por meio da qual serão oferecidos, gratuitamente, cursos técnicos para quem concluiu o Ensino Médio e para estudantes matriculados no Ensino Médio e cursos de formação inicial e continuada ou qualificação profissional.
      </div>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="row">
    <a class="btn btn-primary" data-toggle="collapse" href="#col22" style="width: 600px" aria-expanded="false" aria-controls="col22">
      Expansão da Rede Federal de Educação Profissional, Científica e Tecnológica
    </a>
    <!-- Conteudo -->
    <div class="collapse" id="col22">
      <div class="well">
        ...
      </div>
    </div>
  </div>
</div>