<!-- MENU LATERAL -->
<div class="menu">
  <ul class="lvl1">
   
            <li><a href="/index/macroprocesso">Macroprocesso Bolsa Formação</a></li>
            <li><a href="/index/demandante">Cadastro de Demandantes</a></li>
            <li><a href="/index/pactuacao">Pactuação de Vagas</a></li>
            <li><a href="/index/repactuacao">Repactuação de Vagas</a></li>
            <li><a href="/index/aditarpactuacao">Aditamento de Pactuação</a></li>
            <li><a href="/index/ofertaturmas">Oferta de Turmas</a></li>
            <li><a href="/index/inscricaoonline">Inscrição Online</a></li>
            <li><a href="/index/prematricula">Pré-Matrícula e Matrícula</a></li>
            <li><a href="/index/frequencia">Registro de Frequência</a></li>
  </ul>
</div>
<!-- FIM MENU LATERAL -->

