<!-- MENU LATERAL -->
<div class="menu">
  <ul class="lvl1">
   
            <li><a href="">Habilitação Pronatec</a></li>
            <li class="active"><a href="">Bolsa-Formação<i class="fa fa-chevron-down pull-right"></i></a>
		        <ul class="lvl2">
		            <li><a href="">Parceiros Demandantes</a></li>
		            <li><a href="">Pactuações</a></li>
		            <li><a href="/pronatec/ofertaturma">Ofertas</a></li>
		            <li><a href="">Pré-Matriculas</a></li>
		            <li><a href="">Inscrição Online</a></li>
		            <li><a href="">Matrículas</a></li>
		            <li><a href="">Frequências</a></li>
		            <li><a href="">Confirmação de Frequências</a></li>	
		        </ul>
    		</li>
    		<li class="active"><a href="">Sisutec<i class="fa fa-chevron-down pull-right"></i></a>
		        <ul class="lvl2">
		            <li><a href="">Adesão</a></li>
		            <li><a href="">Proposta de Ofertas de Vagas</a></li>
		            <li><a href="">Incrição</a></li>
		            <li><a href="">Matrículas</a></li>
		            <li><a href="">Vagas Remanescentes</a></li>
		            <li><a href="">Pagamento de Mantenedoras Privadas</a></li>
		        </ul>
    		</li>
    		<li><a href="">Prestação de Contas</a></li>
  </ul>
</div>
<!-- FIM MENU LATERAL -->

