<!-- MENU LATERAL -->
<div class="menu-topo">
	
  <ul class="lvl1">
  <b>
   <li class="scroll" style="width: 344px">&nbsp;</li>
   <li class="scroll"><a href="/administracao">Administração</a></li>
   <li><a class="scroll" href="/calendario">Calendário</a></li>
   <li><a class="scroll" href="/">Ciclo de Matrícula</a></li>
   <li><a class="scroll" href="/">Currículo do Trabalhador</a></li>
   <li><a class="scroll" href="/">E-Tec</a></li>
   <li><a class="scroll" href="/">Habilitação E-Tec</a></li>
   <li><a class="scroll" href="/">Cursos</a></li>
   <li><a class="scroll" href="/">Órgão Validador</a></li>
   <li><a class="scroll" href="/pronatec">Pronatec</a></li>
   <li><a class="scroll" href="/">Unidade de Ensino</a></li>
   </b>
  </ul>
</div>
<div class="menu">
  <ul class="lvl1">
   
            <li><a href="/administracao/usuarios">Usuários</a></li>
            <li><a href="">Relatório</a></li>
            <li><a href="">Consulta de Cursos</a></li>
            <li><a href="">Agrupadores</a></li>
            <li><a href="">Tramitação de Unidades de Ensino</a></li>
            <li><a href="">Tramitação de Cursos Técnicos</a></li>
            <li><a href="">Código de Acesso Inicial</a></li>
            <li><a href="">Aluno Extemporâneo</a></li>
            <li><a href="">Tabelas de Apoio</a></li>
            <li><a href="">Instituto Federal</a></li>
            <li><a href="">Adesão E-tec</a></li>
            <li><a href="">Adesão Sisu Técnico</a></li>
  </ul>
</div>
<!-- FIM MENU LATERAL -->

